columns:
  - width: 1/2
    sections:
      albums: sections/albums

  - width: 1/2
    sections:
      notes:
        extends: sections/notes
        status: listed

      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default

      # Ab hier ist der Footer-Bereich:
      footer_section:
        type: fields
        fields:
          footer_text:
            label: Fußnote (Inhalt)
            type: textarea
            size: small
            buttons:
              - bold
              - italic
              - link