# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

tabs:
  # --- TAB 1: SEITEN ---
  pagesTab:
    label: Seiten
    icon: page
    sections:
      pages:
        type: pages
        create: default
        templates:
          - home
          - default
          - about
          - authors
          - projekte
          - projekt-raphael
          - projekt-default
          - projekt-sabrina
          - projekt-sarah
          - legal
